server:
  port: 8050
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

spring:
  sleuth:
    sampler:
      rate: 100
  kafka:
    bootstrap-servers: localhost:9092
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: kafka

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG


